// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": public TestHelpers
//
// Command:
// $ goagen
// --design=github.com/Gys/goa-cellar/design
// --out=$(GOPATH)/src/github.com/Gys/goa-cellar
// --version=v1.3.1

package test
