consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Account:
    description: A tenant account (default view)
    example:
      created_at: 2015-09-23T11:51:57-07:00
      created_by: loyce.doyle@pollich.com
      href: Et ut omnis praesentium non.
      id: 6.955004e+18
      name: Explicabo laboriosam consequatur.
    properties:
      created_at:
        description: Date of creation
        example: 2015-09-23T11:51:57-07:00
        format: date-time
        type: string
      created_by:
        description: Email of account owner
        example: loyce.doyle@pollich.com
        format: email
        type: string
      href:
        description: API href of account
        example: Et ut omnis praesentium non.
        type: string
      id:
        description: ID of account
        example: 6.955004e+18
        format: int64
        type: integer
      name:
        description: Name of account
        example: Explicabo laboriosam consequatur.
        type: string
    required:
    - id
    - href
    - name
    - created_at
    - created_by
    title: 'Mediatype identifier: application/vnd.account+json'
    type: object
  AccountCollection:
    description: AccountCollection is the media type for an array of Account (default
      view)
    example:
    - created_at: 2015-09-23T11:51:57-07:00
      created_by: loyce.doyle@pollich.com
      href: Et ut omnis praesentium non.
      id: 6.955004e+18
      name: Explicabo laboriosam consequatur.
    - created_at: 2015-09-23T11:51:57-07:00
      created_by: loyce.doyle@pollich.com
      href: Et ut omnis praesentium non.
      id: 6.955004e+18
      name: Explicabo laboriosam consequatur.
    items:
      $ref: '#/definitions/Account'
    title: 'Mediatype identifier: application/vnd.account+json; type=collection'
    type: array
  AccountLink:
    description: A tenant account (link view)
    example:
      created_at: 2015-09-23T11:51:57-07:00
      created_by: loyce.doyle@pollich.com
      href: Et ut omnis praesentium non.
      id: 6.955004e+18
      name: Explicabo laboriosam consequatur.
    properties:
      href:
        description: API href of account
        example: Et ut omnis praesentium non.
        type: string
      id:
        description: ID of account
        example: 6.955004e+18
        format: int64
        type: integer
    required:
    - id
    - href
    title: 'Mediatype identifier: application/vnd.account+json'
    type: object
  Bottle:
    description: A bottle of wine (default view)
    example:
      account:
        created_at: 2015-09-23T11:51:57-07:00
        created_by: loyce.doyle@pollich.com
        href: Et ut omnis praesentium non.
        id: 6.955004e+18
        name: Explicabo laboriosam consequatur.
      color: white
      country: sok
      created_at: 1997-07-28T18:41:27-07:00
      href: Enim suscipit est explicabo eveniet dolore.
      id: 7.9748073e+18
      name: 6h
      rating: 3
      region: Veniam fugit.
      review: qzxmvof
      sweetness: 3
      updated_at: 1999-05-09T06:21:29-07:00
      varietal: d2xq5
      vineyard: 6r6y
      vintage: 1982
    properties:
      account:
        $ref: '#/definitions/Account'
      href:
        description: API href of bottle
        example: Enim suscipit est explicabo eveniet dolore.
        type: string
      id:
        description: ID of bottle
        example: 7.9748073e+18
        format: int64
        type: integer
      links:
        $ref: '#/definitions/BottleLinks'
      name:
        example: 6h
        minLength: 2
        type: string
      rating:
        description: Rating of bottle between 1 and 5
        example: 3
        maximum: 5
        minimum: 1
        type: integer
      varietal:
        example: d2xq5
        minLength: 4
        type: string
      vineyard:
        example: 6r6y
        minLength: 2
        type: string
      vintage:
        example: 1982
        maximum: 2020
        minimum: 1900
        type: integer
    required:
    - id
    - href
    - name
    - vineyard
    - varietal
    - vintage
    title: 'Mediatype identifier: application/vnd.bottle+json'
    type: object
  BottleCollection:
    description: BottleCollection is the media type for an array of Bottle (default
      view)
    example:
    - account:
        created_at: 2015-09-23T11:51:57-07:00
        created_by: loyce.doyle@pollich.com
        href: Et ut omnis praesentium non.
        id: 6.955004e+18
        name: Explicabo laboriosam consequatur.
      href: Enim suscipit est explicabo eveniet dolore.
      id: 7.9748073e+18
      links:
        account:
          href: Et ut omnis praesentium non.
          id: 6.955004e+18
      name: 6h
      rating: 3
      varietal: d2xq5
      vineyard: 6r6y
      vintage: 1982
    - account:
        created_at: 2015-09-23T11:51:57-07:00
        created_by: loyce.doyle@pollich.com
        href: Et ut omnis praesentium non.
        id: 6.955004e+18
        name: Explicabo laboriosam consequatur.
      href: Enim suscipit est explicabo eveniet dolore.
      id: 7.9748073e+18
      links:
        account:
          href: Et ut omnis praesentium non.
          id: 6.955004e+18
      name: 6h
      rating: 3
      varietal: d2xq5
      vineyard: 6r6y
      vintage: 1982
    items:
      $ref: '#/definitions/Bottle'
    title: 'Mediatype identifier: application/vnd.bottle+json; type=collection'
    type: array
  BottleLinks:
    description: BottleLinks contains links to related resources of Bottle.
    properties:
      account:
        $ref: '#/definitions/AccountLinkLink'
    title: BottleLinks
    type: object
  CreateAccountPayload:
    properties:
      name:
        description: Name of account
        type: string
    required:
    - name
    title: CreateAccountPayload
    type: object
  CreateBottlePayload:
    properties:
      color:
        enum:
        - red
        - white
        - rose
        - yellow
        - sparkling
        type: string
      country:
        minLength: 2
        type: string
      name:
        minLength: 2
        type: string
      region:
        type: string
      review:
        maxLength: 300
        minLength: 3
        type: string
      sweetness:
        maximum: 5
        minimum: 1
        type: integer
      varietal:
        minLength: 4
        type: string
      vineyard:
        minLength: 2
        type: string
      vintage:
        maximum: 2020
        minimum: 1900
        type: integer
    required:
    - name
    - vineyard
    - varietal
    - vintage
    - color
    title: CreateBottlePayload
    type: object
  RateBottlePayload:
    properties:
      rating:
        description: Rating of bottle between 1 and 5
        maximum: 5
        minimum: 1
        type: integer
    required:
    - rating
    title: RateBottlePayload
    type: object
  UpdateAccountPayload:
    properties:
      name:
        description: Name of account
        type: string
    required:
    - name
    title: UpdateAccountPayload
    type: object
  UpdateBottlePayload:
    properties:
      color:
        enum:
        - red
        - white
        - rose
        - yellow
        - sparkling
        type: string
      country:
        minLength: 2
        type: string
      name:
        minLength: 2
        type: string
      region:
        type: string
      review:
        maxLength: 300
        minLength: 3
        type: string
      sweetness:
        maximum: 5
        minimum: 1
        type: integer
      varietal:
        minLength: 4
        type: string
      vineyard:
        minLength: 2
        type: string
      vintage:
        maximum: 2020
        minimum: 1900
        type: integer
    title: UpdateBottlePayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error'
    type: object
externalDocs:
  description: goa guide
  url: http://goa.design/getting-started.html
host: localhost:8081
info:
  contact:
    email: admin@goa.design
    name: goa team
    url: http://goa.design
  description: A basic example of a CRUD API implemented with goa
  license:
    name: MIT
    url: https://github.com/goadesign/goa/blob/master/LICENSE
  title: The virtual wine cellar
  version: ""
paths:
  /cellar/accounts:
    get:
      description: Retrieve all accounts.
      operationId: account#list
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AccountCollection'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list account
      tags:
      - account
    post:
      description: Create new account
      operationId: account#create
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateAccountPayload'
      responses:
        "201":
          description: Resource created
          headers:
            Location:
              description: href to created resource
              pattern: /accounts/[0-9]+
              type: string
      schemes:
      - http
      summary: create account
      tags:
      - account
  /cellar/accounts/{accountID}:
    delete:
      operationId: account#delete
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      schemes:
      - http
      summary: delete account
      tags:
      - account
    get:
      description: Retrieve account with given id. IDs 1 and 2 pre-exist in the system.
      operationId: account#show
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Account'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show account
      tags:
      - account
    put:
      description: Change account name
      operationId: account#update
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: integer
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UpdateAccountPayload'
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      schemes:
      - http
      summary: update account
      tags:
      - account
  /cellar/accounts/{accountID}/bottles:
    get:
      description: List all bottles in account optionally filtering by year
      operationId: bottle#list
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: integer
      - description: Filter by years
        in: query
        items:
          type: integer
        name: years
        required: false
        type: array
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/BottleCollection'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list bottle
      tags:
      - bottle
    post:
      description: Record new bottle
      operationId: bottle#create
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: integer
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateBottlePayload'
      responses:
        "201":
          description: Resource created
          headers:
            Location:
              description: href to created resource
              pattern: ^/accounts/[0-9]+/bottles/[0-9]+$
              type: string
        "404":
          description: Not Found
      schemes:
      - http
      summary: create bottle
      tags:
      - bottle
  /cellar/accounts/{accountID}/bottles/{bottleID}:
    delete:
      operationId: bottle#delete
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: integer
      - in: path
        name: bottleID
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      schemes:
      - http
      summary: delete bottle
      tags:
      - bottle
    get:
      description: Retrieve bottle with given id
      operationId: bottle#show
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: integer
      - in: path
        name: bottleID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Bottle'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show bottle
      tags:
      - bottle
    patch:
      operationId: bottle#update
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: integer
      - in: path
        name: bottleID
        required: true
        type: integer
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UpdateBottlePayload'
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      schemes:
      - http
      summary: update bottle
      tags:
      - bottle
  /cellar/accounts/{accountID}/bottles/{bottleID}/actions/rate:
    put:
      operationId: bottle#rate
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: integer
      - in: path
        name: bottleID
        required: true
        type: integer
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/RateBottlePayload'
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      schemes:
      - http
      summary: rate bottle
      tags:
      - bottle
  /cellar/accounts/{accountID}/bottles/{bottleID}/watch:
    get:
      description: Retrieve bottle with given id
      operationId: bottle#watch
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: integer
      - in: path
        name: bottleID
        required: true
        type: integer
      responses:
        "101":
          description: Switching Protocols
      schemes:
      - ws
      summary: watch bottle
      tags:
      - bottle
  /js/{filepath}:
    get:
      operationId: public#/js/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: Download public/js/
  /schema.json:
    get:
      operationId: public#/schema.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download public/schema/schema.json
  /swagger.json:
    get:
      operationId: public#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download public/swagger/swagger.json
  /ui:
    get:
      operationId: public#/ui
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download public/html/index.html
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NoContent:
    description: No Content
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Account'
  SwitchingProtocols:
    description: Switching Protocols
schemes:
- http
swagger: "2.0"
